### ISSUE TITLE
Archive the project?

### ISSUE THREAD

**Issue by notFloran** [TheRedDot/MergeRequestsCI#31]
I think we can archive the project :

* @nclsHart and me use https://github.com/TheGrowingPlant/gitlab-reviewer
* @martin-damien use https://github.com/martin-damien/requests-overview

**Comment by nclsHart** [comment]
I agree.
But we should do this the right way and "redirect" interested users to this two maintained projects.

**Comment by ghost** [comment]
We use merge request CI on personal computers.

Requests-overview has been developed for wall fixed displays only.

Maybe could we keep this project alive until February 2020. It will be useless (not needed anymore for us) after that (I think you know why @notFloran @nclsHart ).

**Comment by notFloran** [comment]
> Maybe could we keep this project alive

No problem for me

> alive until February 2020. It will be useless (not needed anymore for us) after that (I think you know why @notFloran @nclsHart ).

![noidea](https://user-images.githubusercontent.com/523981/70427874-ccf00800-1a75-11ea-831f-b31d5c9d873a.gif)

**Comment by ghost** [comment]
Something wicked comes. But I can’t speak about it for now. (I though DD told you).

Stay tuned.

**Comment by notFloran** [comment]
![humm](https://user-images.githubusercontent.com/523981/70458792-24f92f80-1ab3-11ea-9b0d-e0b2e7c540ce.gif)

**Comment by ghost** [comment]
I think you can shutdown the netlify runner. Nobody uses it anymore at our office.

**Comment by notFloran** [comment]
Ok, I will archive the project.

Bye bye MergeRequestsCI
